### ISSUE TITLE
Feather Huzzah ESP8266 doesn't work w/ Grove adapter

### ISSUE THREAD

**Issue by tamberg** [tamberg/fhnw-iot#1]
The Feather Huzzah ESP8266 board seems to reset if used with Particle Grove adapter.

The board keeps rebooting after a short while (check the serial output).

I'm still investigating the issue, maybe a pin pulled to GND.

(The issue only applies to this board.)

**Comment by tamberg** [comment]
> My Huzzah board keeps crashing and resetting, whats up with that?

> The most common reason for crashes is power failure. Make sure you're powering the Huzzah with a good ~5V power supply, and if you're using a USB-Serial cable, that it's plugged into the mainboard of your computer or through a powered hub!

https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/faq#faq-2

(Not sure, via USB-C it should get enough power.)

**Comment by tamberg** [comment]
https://community.particle.io/t/particle-mesh-starter-kit-grove-adapter-issue/48059

**Comment by tamberg** [comment]
https://community.particle.io/uploads/default/original/3X/f/5/f53141349fdb736887dbd6e5bc55586220be32ba.png via https://community.particle.io/t/particle-mesh-starter-kit-grove-adapter-issue/48059/2

**Comment by okaerin** [comment]
According to adafruit the CH_PD pin needs to be pulled high or else the board resets. This is violated by the particle mesh board as it connects the pin to GND. It can be solved by bending the CH_PD pin away
https://learn.adafruit.com/adafruit-feather-huzzah-esp8266/pinouts/

**Comment by tamberg** [comment]
Very nice, thanks! Then the fix is to (slowly) bend the CHPD pin towards the inside as shown here:
![image](https://user-images.githubusercontent.com/142092/57792345-0f9b6d00-773f-11e9-9ceb-8de769604f82.png)

**Comment by tamberg** [comment]
Here's a better fix: 
![image](https://live.staticflickr.com/65535/48307053192_03217a9230.jpg)

**Comment by tamberg** [comment]
And a pragmatic fix, which consumes a bit more energy, using a jumper cable:
![image](https://live.staticflickr.com/65535/48299314666_c644a56c66_z.jpg)
