### ISSUE TITLE
DHT11 Module is unreliable with 3.3V power supply

### ISSUE THREAD

**Issue by chdabre** [tamberg/fhnw-iot#3]
Tested on Feather nRF52 w/ Grove adapter for Particle Mesh.

**Comment by tamberg** [comment]
Maybe this helps? https://github.com/tamberg/fhnw-iot/issues/5

**Comment by tamberg** [comment]
See https://github.com/tamberg/fhnw-iot/wiki/Grove-Sensors#temperature--humidity-sensor-dht11 > Code > Arduino > nRF52840
