### ISSUE TITLE
Adafruit Repository URL is no longer current

### ISSUE THREAD

**Issue by jmesserli** [tamberg/fhnw-iot#30]
The page https://github.com/tamberg/fhnw-iot/wiki/Feather-nRF52840-Express#setup-for-experts refers to `https://www.adafruit.com/package_adafruit_index.json` for the additional Adafruit boards.

The new URL is `https://adafruit.github.io/arduino-board-index/package_adafruit_index.json`, source: https://github.com/adafruit/Adafruit_nRF52_Arduino#recommended-adafruit-nrf52-bsp-via-the-arduino-board-manager

**Comment by tamberg** [comment]
Fixed, thanks!
