### ISSUE TITLE
Linux Adafruit nRF52840 Express adafruit-util Flash-Probleme

### ISSUE THREAD

**Issue by okaerin** [tamberg/fhnw-iot#8]
Unter Linux stört der ModemManager das adafruit-util. Das führt dazu, dass Flashes nur sporadisch funktionieren und mit mehrfachen Resets. Gelöst werden kann es mit:

`sudo bash -c "systemctl stop ModemManager&&systemctl disable ModemManager"`

**Comment by tamberg** [comment]
Ist jetzt so im Wiki, danke.
